name: ESLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: sudo npm install eslint@8.57.0 -g
    - name: Run ESLint
      run: eslint . -f tap --ext .js,.jsx,.ts,.tsx
